### ISSUE TITLE
Multiple selection sample or guide

### ISSUE THREAD

**Issue by revoman** [albertino80/bppgrid#2]
Hello,
Thank you for sharing such this great qt project.
I'm learnnig QT and your codes are very helpful to understand qml quick2 table view.
I have looked this sample at the last time.

https://dev.bigno.it/bppgrid/multiselection.gif

Could you share above example program?
Thank you.

**Comment by albertino80** [comment]
Thanks for feedback, see the updated README.md

**Comment by revoman** [comment]
Thanks for your help! It would be very helpful.
