### ISSUE TITLE
Implementing model for CompGrid (Question)

### ISSUE THREAD

**Issue by noobaldrin** [albertino80/bppgrid#5]
I don't want to hit a brick wall before I start making my own so I'm going to ask, how do you deal with models using bppgrid?

Can I create my own QAbstractTableModel or should I inherit from bpp::TableModel?

**Comment by albertino80** [comment]
The grid is populated using one of the methods:
* fillFromArray (for js array of array, representing cells)
* fillFromQuery (for Db query)
* fillFromJson (for js array of js objects)
* fillFromListModel (for a ListModel)

You don't have to create a model class to use the grid. What's your use case?

**Comment by noobaldrin** [comment]
> The grid is populated using one of the methods:
> 
>     * fillFromArray (for js array of array, representing cells)
> 
>     * fillFromQuery (for Db query)
> 
>     * fillFromJson (for js array of js objects)
> 
>     * fillFromListModel (for a ListModel)
> 
> 
> You don't have to create a model class to use the grid. What's your use case?

Sorry if I'm lacking the knowledge of C++/QML integration but here's what I'm doing or would like to do:

So I have multitab application using your grid.
I have a C++/Qt object that will be instantiated for each tabs.

Is it possible to use fillFromJson(backend.cppfunction())
where backend.cppfunction() is Q_INVOKABLE that returns a JSON object?

I haven't worked on my personal project for a while but I'd just like to see if that's gonna work.

**Comment by albertino80** [comment]
If it helps, I have added a new example: `with_json_cpp_be` where I show you the usage of the grid in a multitab app with cpp backend

**Comment by noobaldrin** [comment]
> If it helps, I have added a new example: `with_json_cpp_be` where I show you the usage of the grid in a multitab app with cpp backend

Oh sweet. Now it makes a lot more sense.
Thanks a lot. I'm closing this "issue" now. :)
